name: Python CI/CD to Google Artifact Registry and Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker europe-central2-docker.pkg.dev

    - name: Build and Push Docker image to Artifact Registry
      run: |
        docker build -t europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sdg/sdg:latest .
        docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sdg/sdg:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Authenticate to Google Cloud (Again if needed)
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup GCP Credentials
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo "$SERVICE_ACCOUNT_KEY" | base64 --decode > "$HOME"/gcloud-service-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-service-key.json" >> $GITHUB_ENV

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy sdg \
          --image europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sdg/sdg:latest \
          --region europe-central2 \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --set-env-vars \
              BUCKET_NAME=${{ secrets.BUCKET_NAME }},\
              GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }},\
              GCS_CLOUD_TOPIC_ID=${{ secrets.GCS_CLOUD_TOPIC_ID }},\
              BQ_CLOUD_TOPIC_ID=${{ secrets.BQ_CLOUD_TOPIC_ID }} \
          --service-account ${{ secrets.SERVICE_ACCOUNT }}
