name: Python CI/CD to Google Artifact Registry and Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker image to Artifact Registry
      run: |
        gcloud auth configure-docker europe-central2-docker.pkg.dev
        docker build -t synthetic-data-generator .
        docker tag synthetic-data-generator europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sdg/sdg:latest
        docker push europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sdg/sdg:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy sdg --image europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sdg/sdg:latest --region europe-central2 --platform managed --allow-unauthenticated
